---
- name: Install Apache 
  yum: name=httpd state=present 

- name: Start the Apache and Enabled on boot
  service: name=httpd state=started enabled=yes

- name: Enale selinux for http to connect localdb
  seboolean:
    name: httpd_can_network_connect_db 
    state: yes
    persistent: yes

- name: copy the httpd conf
  template: src=httpd-conf.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
   restart httpd

- name: IPtables accept on port 80
  iptables: 
    chain: INPUT
    protocol: tcp 
    destination_port: 80
    jump: ACCEPT
  notify:
   save iptables
  
