---
- name: Install php and other php modules for wordpress 
  yum: name={{item}} state=present
  with_items:
    - php
    - php-pgsql
    - php-mysql
    - php-gd 
    - php-imap 
    - php-ldap 
    - php-odbc 
    - php-pear 
    - php-xml 
    - php-xmlrpc 
    - php-mbstring 
    - php-mcrypt 
    - php-mssql 
    - php-snmp 
    - php-soap 
    - php-tidy 
    - curl 
    - curl-devel
  notify:
   restart httpd
