---
- name: Download wordpress-3.4.2 and untar on source
  unarchive:
   src: https://wordpress.org/wordpress-3.4.2.tar.gz
   dest: /var/www/html/
   remote_src: yes
   owner: root
   group: root

- name: Download Postgresql plugin for Wordpress
  unarchive:
   src: https://downloads.wordpress.org/plugin/postgresql-for-wordpress.1.3.1.zip
   dest: /tmp/
   remote_src: yes

- name: Copy postgresql plugin from /tmp to wp-content
  command: rsync -az /tmp/postgresql-for-wordpress/pg4wp /var/www/html/wordpress/wp-content/plugins/ 

- name: Copy the db.php from the pg4wp directory to wp-content
  copy: src=/var/www/html/wordpress/wp-content/plugins/pg4wp/db.php dest=/var/www/html/wordpress/wp-content/ remote_src=yes 

- name: Copy the wp-config to /var/www/html/wordpress/
  copy: src=wp-config.php dest=/var/www/html/wordpress/
  notify:
   restart httpd
